#!/bin/sh
cd "${0%/*}" || exit        # Run from this directory

particleDiameter="0.0002"   # Snow particle diameter 
                            # 雪颗粒粒径

nParticleInParcel="5000"    # Number of particles in one parcel 
                            # 单个颗粒团中的雪颗粒个数

virtualSnowHeight="1.0"     # Maximum height when initialize the snow particle use ManualInjection 
                            # 初始化颗粒时的最大高度

shearVelocity="0.35"         # Friction velocity 
                            # 剪切风速

# Get a steady flow in cyclic ABL
# 计算周期大气层边界的稳态流场(粗网格)
echo "Now run case_steady in coarsen..."
cd case_steady_coarsen
sed "s|SHEAR_VEL|$shearVelocity|g" 0.orig/include/ABLConditions.template > \
    0.orig/include/ABLConditions
./Allrun
cd ..

# Get a steady flow in cyclic ABL
# 计算周期大气层边界的稳态流场
echo "\nNow run case_steady..."
cd case_steady
sed "s|SHEAR_VEL|$shearVelocity|g" 0.orig/include/ABLConditions.template > \
    0.orig/include/ABLConditions
./Allrun-parallel
cd ..

# Get a packed snow bed
# 计算雪颗粒的堆积
#cd ../case_packing
#./Allrun-parallel

# simulate the drifting snow
# 计算风致雪漂
#cd ../case_drifting
#./Allrun-parallel
