#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

rasModel="kOmegaSST"    # Tested options="kOmegaSST","kEpsilon"

sed "s|RAS_MODEL|$rasModel|g" constant/turbulenceProperties.template > \
    constant/turbulenceProperties.air

python3 packing.py -d 0.0002 -nP 5000 -h 0.15

runApplication blockMesh

runApplication decomposePar

#runParallel renumberMesh -overwrite

runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
