#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rasModel="kOmegaSST"    # Tested options="kOmegaSST","kEpsilon"

sed "s|RAS_MODEL|$rasModel|g" constant/turbulenceProperties.template > \
    constant/turbulenceProperties

restore0Dir

runApplication blockMesh

runApplication $(getApplication)

#------------------------------------------------------------------------------
