#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

rasModel="kEpsilon"    # Tested options="kOmegaSST","kEpsilon"

sed "s|RAS_MODEL|$rasModel|g" constant/turbulenceProperties.template > \
    constant/turbulenceProperties

python3 packing.py

runApplication blockMesh

runApplication decomposePar

runParallel mapFields ../case_packing -sourceTime latestTime

runParallel mapFields ../case_steady -sourceTime latestTime

runParallel renumberMesh -overwrite

runParallel $(getApplication)

#runParallel redistributePar -reconstruct -latestTime

#------------------------------------------------------------------------------
