#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

rasModel="kOmegaSST"    # Tested options="kOmegaSST","kEpsilon"

sed "s|RAS_MODEL|$rasModel|g" constant/turbulenceProperties.template > \
    constant/turbulenceProperties.air

python3 packing.py

runApplication blockMesh

#runApplication setFields
runApplication mapFields ../case_packing -sourceTime latestTime 
mv log.mapFields log.mapFields_lagrangian
runApplication mapFields ../case_steady -sourceTime latestTime

runApplication decomposePar

#runParallel renumberMesh -overwrite

#runParallel $(getApplication)

#runParallel redistributePar -reconstruct -latestTime

#------------------------------------------------------------------------------
